/**
 * Stable Rinspace application boundary for the pinned, owned Animate UI layer.
 * Page and feature code import from `components/ui`; provenance stays encapsulated here.
 */
export {
  AnimateAvatarGroup,
  AnimateButton,
  AnimateCheckbox,
  AnimateCodeTabs,
  AnimateCopyButton,
  Code,
  CodeBlock,
  CodeHeader,
  AnimateFiles,
  AnimateHoverCard,
  AnimateHoverCardArrow,
  AnimateHoverCardContent,
  AnimateHoverCardTrigger,
  AnimateGithubStars,
  AnimateIconButton,
  AnimateImageZoom,
  AnimatePreviewLinkCard,
  AnimateProgress,
  AnimateScrollProgress,
  AnimateSidebar,
  AnimateSidebarContent,
  AnimateSidebarFooter,
  AnimateSidebarHeader,
  AnimateSidebarInset,
  AnimateSidebarMenu,
  AnimateSidebarMenuBadge,
  AnimateSidebarMenuButton,
  AnimateSidebarMenuItem,
  AnimateSidebarProvider,
  AnimateSidebarTrigger,
  SplittingText,
  AnimateSwitch,
  AnimateTabs,
  AnimateTabsContent,
  AnimateTabsList,
  AnimateTabsTrigger,
  AnimateThemeToggler,
  UserPresenceAvatar,
  rinMotion,
  useAnimateSidebar,
} from "@/components/animate-ui";
export {
  ArrowUpRight as AnimateArrowUpRight,
  Bell as AnimateBell,
  BellRing as AnimateBellRing,
  ChartSpline as AnimateChartSpline,
  ChevronDown as AnimateChevronDown,
  CircleAlert as AnimateCircleAlert,
  Cross as AnimateCross,
  Clipboard as AnimateClipboard,
  Clock as AnimateClock,
  HeartHandshake as AnimateHeartHandshake,
  Kanban as AnimateKanban,
  LayoutDashboard as AnimateLayoutDashboard,
  LogOut as AnimateLogOut,
  MessageCircleWarning as AnimateMessageCircleWarning,
  Paintbrush as AnimatePaintbrush,
  PanelLeft as AnimatePanelLeft,
  Plus as AnimatePlus,
  Search as AnimateSearch,
  Settings as AnimateSettings,
  Sparkles as AnimateSparkles,
  Star as AnimateStar,
  Terminal as AnimateTerminal,
  ThumbsDown as AnimateThumbsDown,
  ThumbsUp as AnimateThumbsUp,
  User as AnimateUser,
  Wallet as AnimateWallet,
  Filter as AnimateFilter,
  GitCommit as AnimateGitCommit,
  History as AnimateHistory,
  More as AnimateMore,
  Refresh as AnimateRefresh,
  ShieldCheck as AnimateShieldCheck,
} from "@/components/animate-ui/icons";
export type {
  AnimateButtonProps,
  AnimateButtonSize,
  AnimateButtonVariant,
  AnimateIconButtonProps,
  AnimateGithubStarsProps,
  AnimateFileNode,
  AvatarIdentity,
  CodeBlockProps,
  CodeHeaderProps,
  CodeProps,
  SplittingTextProps,
  UserPresenceAvatarItem,
} from "@/components/animate-ui";
